### ISSUE TITLE
Duplicate publication records in GUDMAP/RBK 

### ISSUE THREAD

**Issue by animesh-bhadouria** [informatics-isi-edu/gudmap-rbk#1]
@crisaless 

There are 4 records for the same publication in the database.

**Publication Title:** 
> Mouse brain organization revealed through direct genome-scale TF expression analysis.

**RID's:**  S-2M8E, S-2M8T, S-2M8Y, S-2M9E

https://www.gudmap.org/chaise/recordset/#2/Common:Publication@sort(RID)

Attached Screenshot:

![duplicates](https://user-images.githubusercontent.com/7467458/58673030-70f63b00-82fe-11e9-8d6c-c8c8f4763c66.JPG)

**Comment by crisaless** [comment]
I see you closed this issue already. I just now took a look at this and it does seem like the same publication is duplicated but with different data records linked to them? Will these be integrated into one publication?

**Comment by animesh-bhadouria** [comment]
@crisaless : I had accidentally created this issue on the incorrect repository so I closed this and created a new one here: https://github.com/informatics-isi-edu/rbk-project/issues/574
